# Generated by Django 3.1.1 on 2020-10-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_shippingadress_contry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='contry',
            new_name='country',
        ),
    ]
