# Generated by Django 3.1.1 on 2020-10-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_couontrycodes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouontryCodes',
            new_name='CountryCodes',
        ),
    ]
